import React,{useEffect,useRef,useState} from 'react';
import {Link,Navigate,Outlet,useLocation,useNavigate} from 'react-router-dom';
import {ArrowLeft,ArrowRight,ArrowUpRight,Handshake,CheckCircle2,ShieldCheck} from 'lucide-react';
import {Btn} from '../components/Common';
import {Shell} from '../components/Shell';
import {useDemo} from '../demo/store';
import {useAuth} from './store';
import {Role,panels,panelRoles,canRegister,registrationFields,validateRegistration,Registration,FieldSpec} from './config';
import './entry.css';
export const PrototypeBanner=()=> <div className="entry-banner" data-testid="prototype-banner">Interactive prototype · synthetic data · no live transactions.</div>;
const Brand=()=> <Link to="/" className="entry-brand" data-testid="entry-brand"><span className="brand-icon"><Handshake size={26}/></span><span>LABOURLINK<small>BETTER WORK. TOGETHER.</small></span></Link>;
export function Landing(){return <div className="entry-page"><header className="entry-header"><Brand/><span className="entry-preview" data-testid="entry-scenario">LOCAL PREVIEW <i/> LL-DEMO-01</span></header><main className="entry-main" id="entry-main"><div className="entry-intro"><p className="eyebrow">PEOPLE FIRST. COOPERATIVE ALWAYS.</p><h1 data-testid="landing-title">One cooperative<br/>ecosystem</h1><p data-testid="landing-subtitle">Six distinct experiences · shared synthetic scenario in this local preview.</p></div><div className="entry-grid">{panelRoles.map((role,i)=>{const panel=panels[role],Icon=panel.icon;return <Link key={role} to={`/${role}/login`} className="entry-role" data-testid={`entry-${role}`} style={{animationDelay:`${i*45}ms`}}><span className="entry-role-icon"><Icon size={26} strokeWidth={1.6}/></span><div><h2>{panel.title}</h2><p>{panel.description}</p></div><ArrowUpRight size={20} className="entry-arrow" aria-hidden="true"/></Link>;})}</div><p className="entry-boundary" data-testid="entry-disclosure"><ShieldCheck size={19}/>Separate sites require explicit export/import. Role switching here is a demonstration, not secure authorization.</p></main></div>;}
export function RequirePanel(){
 const {pathname}=useLocation(),{session}=useAuth(),{state}=useDemo();const role=pathname.split('/')[1] as Role;
 if(!session?.isAuthenticated||session.role!==role)return <Navigate to={`/${role}/login`} replace/>;
 const missingWorker=role==='worker'&&!state.entities.workers.some(w=>w.id===session.accountId);
 return <Shell key={`${role}-${session.accountId}`}>{missingWorker?<div data-testid="missing-worker-fixture" className="notice caution">Your account is still saved, but this scenario no longer contains your worker profile. Use Demo tools to import your saved scenario, or log out to use a seeded demo account.</div>:<Outlet/>}</Shell>;
}
function AuthFrame({role,title,children}:{role:Role;title:string;children:React.ReactNode}){
 const panel=panels[role],Icon=panel.icon;
 return <div className="entry-page"><header className="entry-header"><Brand/><Link to="/" data-testid="auth-back-ecosystem" className="entry-back"><ArrowLeft size={16}/>All experiences</Link></header><main className="auth-layout"><aside className="auth-context"><span className="auth-context-icon"><Icon size={33} strokeWidth={1.5}/></span><p className="eyebrow" data-testid="auth-role">{panel.title.toUpperCase()} WORKSPACE</p><h1 data-testid="auth-context-title">{panel.description}</h1><p>One local scenario.<br/>A distinct space for your role.</p><div className="auth-context-note" data-testid="auth-local-notice"><ShieldCheck size={20}/><span>Simulated access only. Use fictional details and a demo-only password. Nothing here verifies a real identity.</span></div></aside><section className="auth-card" aria-labelledby="auth-title"><div className="auth-heading"><span className="eyebrow">LABOURLINK / {panel.title.toUpperCase()}</span><h2 id="auth-title" data-testid="auth-title">{title}</h2></div>{children}</section></main></div>;
}
function AuthField({field,value,onChange,error,prefix}:{field:FieldSpec;value:string;onChange:(value:string)=>void;error?:string;prefix:string}){
 const id=`${prefix}-${field.key}`;return <div className="auth-field"><label htmlFor={id} data-testid={`${id}-label`}>{field.label}{field.optional&&<span> (optional)</span>}</label><input id={id} data-testid={id} type={field.type||'text'} value={value} onChange={e=>onChange(e.target.value)} autoComplete={field.autoComplete||'off'} maxLength={field.type==='password'?128:100} min={field.type==='number'?0:undefined} max={field.type==='number'?70:undefined} step={field.type==='number'?1:undefined} required={!field.optional} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined}/>{error&&<p className="auth-field-error" id={`${id}-error`} data-testid={`${id}-error`}>{error}</p>}</div>;
}
const AuthError=({message}:{message:string})=>message?<div role="alert" className="auth-error" data-testid="auth-error">{message}</div>:null;
export function Login({role}:{role:Role}){
 const {login,hasWorker}=useAuth(),navigate=useNavigate(),location=useLocation();const [identifier,setIdentifier]=useState(location.state?.identifier||''),[password,setPassword]=useState(''),[errors,setErrors]=useState<Record<string,string>>({}),[error,setError]=useState('');
 const panel=panels[role];
 const submit=(e:React.FormEvent)=>{e.preventDefault();setError('');const next:Record<string,string>={};if(!identifier.trim())next.identifier='Enter your login identifier.';if(!password)next.password='Enter your password.';setErrors(next);if(Object.keys(next).length)return;
  if(role==='worker'&&!hasWorker(identifier)&&!identifier.trim().toUpperCase().startsWith('WRK-')){navigate('/worker/register',{state:{shramCard:identifier,notice:'No local account was found for this Shram Card. Register first using fictional demo details.'}});return;}
  try{login(role,identifier,password);navigate(`/${role}`,{replace:true});}catch(err){setError((err as Error).message);}
 };
 return <AuthFrame role={role} title={`${panel.title} login`}><form onSubmit={submit} noValidate className="auth-form" data-testid={`${role}-login-form`}><AuthField prefix="login" field={{key:'identifier',label:panel.loginLabel,autoComplete:'username'}} value={identifier} onChange={setIdentifier} error={errors.identifier}/>{['household','institution'].includes(role)&&<p className="auth-hint" data-testid="login-id-hint">Your {panel.idLabel} also works in this demo.</p>}<AuthField prefix="login" field={{key:'password',label:'Password',type:'password',autoComplete:'current-password'}} value={password} onChange={setPassword} error={errors.password}/><Link className="auth-link auth-forgot" to={`/${role}/forgot-password`} data-testid="forgot-password">Forgot Password</Link><AuthError message={error}/><Btn id="login-submit" type="submit" className="auth-submit">Login <ArrowRight size={17}/></Btn></form>{canRegister(role)?<Link to={`/${role}/register`} className="auth-register-link" data-testid="open-registration">{panel.registerLabel} <ArrowUpRight size={16}/></Link>:<p className="auth-hint auth-no-register" data-testid="no-public-registration">Assigned demo accounts only · no public registration.</p>}<div className="auth-demo" data-testid="demo-credentials"><strong>PROTOTYPE-ONLY CREDENTIALS</strong><p>Demo login: {panel.demoId} / demo123</p>{role==='worker'&&<p>Ramesh Patel · or SHRM-DEMO-001 / demo123</p>}<small>Local simulation. Not secure authorization. A local password reset changes this account's demo password.</small></div></AuthFrame>;
}
export function Register({role}:{role:Role}){
 const {register}=useAuth(),location=useLocation();const [form,setForm]=useState<Registration>({shramCard:location.state?.shramCard||''}),[errors,setErrors]=useState<Record<string,string>>({}),[error,setError]=useState(''),[created,setCreated]=useState('');const formRef=useRef<HTMLFormElement>(null),successRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(created)successRef.current?.focus();},[created]);
 if(!canRegister(role))return <Navigate to={`/${role}/login`} replace/>;
 const submit=(e:React.FormEvent)=>{e.preventDefault();setError('');const next=validateRegistration(role,form);setErrors(next);if(Object.keys(next).length){requestAnimationFrame(()=>formRef.current?.querySelector<HTMLInputElement>('[aria-invalid="true"]')?.focus());return;}try{setCreated(register(role,form).accountId);setForm({});}catch(err){setError((err as Error).message);}};
 const title=role==='worker'?'Create Worker Account':role==='society'?'Register Society':role==='institution'?'Register Organization':'Create Account';
 return <AuthFrame role={role} title={created?'You’re all set':title}>{created?<div className="auth-success" data-testid="registration-success" role="status" tabIndex={-1} ref={successRef}><CheckCircle2 size={42}/><h3>{role==='worker'?'Worker account created successfully.':role==='society'?'Society registered successfully.':'Account created successfully'}</h3><p>Your {panels[role].idLabel}:</p><strong data-testid="registered-account-id">{created}</strong><p className="auth-hint">Saved in this local preview. Keep your ID for your next login.</p><Link to={`/${role}/login`} state={{identifier:created}} className="auth-primary-link" data-testid="registration-login">Login <ArrowRight size={17}/></Link></div>:<>{location.state?.notice&&<p className="auth-info" data-testid="worker-register-guidance">{location.state.notice}</p>}<form ref={formRef} onSubmit={submit} noValidate className="auth-form" data-testid={`${role}-register-form`}>{registrationFields[role]!.map(field=><AuthField key={field.key} prefix="register" field={field} value={form[field.key]||''} onChange={value=>setForm({...form,[field.key]:value})} error={errors[field.key]}/>)}{role==='worker'&&<p className="auth-hint" data-testid="shram-uniqueness-note">One Shram Card = one Worker ID. Use a fictional card number; no real ID verification takes place.</p>}<AuthError message={error}/><Btn id="register-submit" className="auth-submit" type="submit">{role==='worker'?'Create Worker Account':role==='society'?'Register Society':'Create Account'}<ArrowRight size={17}/></Btn></form><Link to={`/${role}/login`} className="auth-register-link" data-testid="register-back-login">Already have an account? Login</Link></>}</AuthFrame>;
}
export function ForgotPassword({role}:{role:Role}){
 const {resetPassword}=useAuth();const [identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[done,setDone]=useState(false);
 const submit=(e:React.FormEvent)=>{e.preventDefault();setError('');if(!identifier.trim()){setError('Enter your local account identifier.');return;}if(password!==confirm){setError('Passwords do not match.');return;}try{resetPassword(role,identifier,password);setDone(true);setPassword('');setConfirm('');}catch(err){setError((err as Error).message);}};
 return <AuthFrame role={role} title="Reset demo password"><p className="auth-info" data-testid="reset-disclosure">Local simulation only. No email, OTP or identity check will be sent. This directly changes a demo password in this browser.</p>{done?<div className="auth-success" role="status" data-testid="password-reset-success"><CheckCircle2 size={36}/><h3>Demo password updated.</h3><p>Use your new demo password to log in.</p></div>:<form className="auth-form" noValidate onSubmit={submit} data-testid="reset-form"><AuthField prefix="reset" field={{key:'identifier',label:panels[role].loginLabel}} value={identifier} onChange={setIdentifier}/><AuthField prefix="reset" field={{key:'password',label:'New demo password',type:'password',autoComplete:'new-password'}} value={password} onChange={setPassword}/><AuthField prefix="reset" field={{key:'confirm',label:'Confirm Password',type:'password',autoComplete:'new-password'}} value={confirm} onChange={setConfirm}/><AuthError message={error}/><Btn id="reset-submit" className="auth-submit" type="submit">Reset demo password</Btn></form>}<Link to={`/${role}/login`} state={{identifier}} className="auth-register-link" data-testid="reset-back-login">Back to Login <ArrowRight size={16}/></Link></AuthFrame>;
}
