import React,{useState} from 'react';
import Papa from 'papaparse';
import {Download,Upload,Check} from 'lucide-react';
import {useDemo,download} from '../demo/store';
import {makeWorker} from '../pages/Workers';
import {TRADES} from '../demo/seed';
import {Modal,Field,Btn,Notice} from './Common';
const sample='name,trade,experience,area,membershipRef\nNirav Demo,Plumbing,5,Paldi,DEMO-NEW-001\nHetal Demo,Cleaning,3,Satellite,DEMO-NEW-002';
export const RosterImport=({open,onClose}:{open:boolean;onClose:()=>void})=>{
 const {state,act}=useDemo();const [raw,setRaw]=useState(''),[rows,setRows]=useState<Record<string,string>[]>([]),[headers,setHeaders]=useState<string[]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[parsed,setParsed]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false);
 const parse=()=>{const result=Papa.parse<Record<string,string>>(raw.replace(/^\uFEFF/,''),{header:true,skipEmptyLines:'greedy'});if(result.errors.length){setError(result.errors.map(x=>x.message).join('; '));return;}const fields=result.meta.fields||[];setHeaders(fields);setRows(result.data);setMapping(Object.fromEntries(['name','trade','experience','area','membershipRef'].map(k=>[k,fields.includes(k)?k:''])));setParsed(true);setError('');setConfirmed(false);};
 const preview=rows.map((r,i)=>{const value=Object.fromEntries(Object.entries(mapping).map(([key,col])=>[key,(r[col]||'').trim()]));const errors:string[]=[];if(value.name.length<2)errors.push('Name needs at least 2 characters');if(!TRADES.includes(value.trade))errors.push('Unknown trade');if(!value.area)errors.push('Area is required');if(!/^\d+$/.test(value.experience)||Number(value.experience)>70)errors.push('Experience must be 0–70');if(Object.values(value).some(v=>/^[=+@\-\t\r]/.test(v)))errors.push('Formula-like cell content is not accepted');if(value.membershipRef&&(state.entities.workers.some(w=>w.membershipRef===value.membershipRef)||rows.slice(0,i).some(x=>(x[mapping.membershipRef]||'').trim()===value.membershipRef)))errors.push('Duplicate membership reference: review required');const nameWarning=state.entities.workers.some(w=>w.name.toLowerCase()===value.name.toLowerCase());return{value,errors,nameWarning};});const valid=preview.filter(p=>!p.errors.length);
 return <Modal id="roster-import-modal" open={open} onClose={onClose} title="Import worker roster" description="Browser-only CSV import · fictional records only · imported workers require verification." wide><div className="button-row"><Btn id="download-csv-template" kind="secondary" onClick={()=>download('LABOURLINK-roster-template.csv',sample,'text/csv;charset=utf-8')}><Download size={15}/>CSV template</Btn><Btn id="load-sample-csv" kind="ghost" onClick={()=>{setRaw(sample);setParsed(false);}}>Use sample rows</Btn></div><Field id="roster-file" label="CSV file"><input data-testid="roster-file" id="roster-file" type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>1024*1024){setError('Maximum CSV size is 1 MB');return;}setRaw(await f.text());setParsed(false);}}/></Field><Field id="roster-csv" label="Or paste CSV"><textarea data-testid="roster-csv" id="roster-csv" rows={4} value={raw} onChange={e=>{setRaw(e.target.value);setParsed(false);}}/></Field><Btn id="parse-roster" disabled={!raw.trim()} onClick={parse}>Map columns & preview</Btn>{error&&<Notice id="roster-parse-error" tone="error">{error}</Notice>}{parsed&&<><div className="form-grid">{Object.keys(mapping).map(k=><Field key={k} label={k} id={`map-${k}`}><select data-testid={`map-${k}`} id={`map-${k}`} value={mapping[k]} onChange={e=>{setMapping({...mapping,[k]:e.target.value});setConfirmed(false);}}><option value="">Not mapped</option>{headers.map(h=><option key={h}>{h}</option>)}</select></Field>)}</div><div className="table-wrap"><table><thead><tr><th>Row</th><th>Name / trade</th><th>Validation</th></tr></thead><tbody>{preview.map((p,i)=><tr key={i} data-testid={`import-row-${i}`}><td>{i+2}</td><td>{p.value.name}<small className="muted"> · {p.value.trade}</small></td><td>{p.errors.length?<span className="status bad">{p.errors.join('; ')}</span>:<span className="status good">Pending review{p.nameWarning?' · same name exists; not automatically duplicate':''}</span>}</td></tr>)}</tbody></table></div><Notice id="roster-preview-count">{valid.length} valid rows · {preview.length-valid.length} invalid rows excluded. Duplicate names alone do not prove duplicate people.</Notice><label className="checkline"><input data-testid="roster-confirm-review" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed membership references and confirm these are synthetic records.</label><Btn id="save-roster" disabled={!confirmed||!valid.length} onClick={()=>{if(act({type:'workers',workers:valid.map(p=>makeWorker(p.value.name,p.value.trade,p.value.membershipRef,p.value.area,Number(p.value.experience)))})){setRaw('');setParsed(false);onClose();}}}><Upload size={16}/>Import {valid.length} pending records</Btn></>}</Modal>;
};