import React,{useState,useEffect} from 'react';
import {NavLink,Link,useLocation,useNavigate} from 'react-router-dom';
import {LayoutDashboard,Users,ShieldCheck,BriefcaseBusiness,Building2,Wallet,MessageSquare,HeartHandshake,ChartNoAxesCombined,ScrollText,ChevronDown,ChevronRight,Globe2,Bell,Menu,X,PanelsTopLeft,House,HardHat,Network,BookOpen,UserRound,Mic,SlidersHorizontal,Handshake,ArrowUpRight,Search,MapPin} from 'lucide-react';
import {useTranslation} from 'react-i18next';
import {useDemo} from '../demo/store';
import {DemoState} from '../demo/schema';
import {DemoTools} from './DemoTools';
import {Voice} from './Voice';
import {Avatar,Modal,useT} from './Common';
export const roles:DemoState['originApp'][]=['Society','Household','Worker','Institution','District','National'];
export const roleIcon={Society:Building2,Household:House,Worker:HardHat,Institution:BriefcaseBusiness,District:Network,National:Globe2};
const links:Record<string,[string,string,React.ElementType][]>={
 Society:[['Overview','',LayoutDashboard],['Workers','workers',Users],['Verification','verification',ShieldCheck],['Jobs','jobs',BriefcaseBusiness],['Bulk requests','bulk',Building2],['Payments & settlements','payments',Wallet],['Complaints','complaints',MessageSquare],['Welfare','welfare',HeartHandshake],['Planning','planning',ChartNoAxesCombined],['Policies','policies',ScrollText]],
 Household:[['Home','',House],['Services','request',Search],['Bookings','bookings',BriefcaseBusiness],['Help','help',MessageSquare]],
 Worker:[['Home','',House],['Jobs','jobs',BriefcaseBusiness],['Earnings','earnings',Wallet],['Learn','learn',BookOpen],['Profile','profile',UserRound],['Welfare','welfare',HeartHandshake]],
 Institution:[['Overview','',LayoutDashboard],['Bulk requests','requirements',BriefcaseBusiness],['Payments & settlements','finances',Wallet],['Complaints','complaints',MessageSquare]],
 District:[['Overview','',LayoutDashboard],['Affiliations','affiliations',Network],['Bulk requests','requests',BriefcaseBusiness],['Capacity board','capacity',Users],['Allocation','allocation',PanelsTopLeft],['Planning','planning',ChartNoAxesCombined],['Issue log','issues',MessageSquare]],
 National:[['Overview','',LayoutDashboard],['Relationships','relationships',Network],['Regional comparison','regions',ChartNoAxesCombined],['Training needs','training',BookOpen],['Coordination','coordination',Handshake],['Welfare','welfare',HeartHandshake],['Data quality','quality',ShieldCheck]]
};
export const Shell=({children}:{children:React.ReactNode})=>{
 const {pathname}=useLocation(),navigate=useNavigate(),{i18n}=useTranslation(),t=useT(),{state}=useDemo();const segment=pathname.split('/')[1];const role=roles.find(r=>r.toLowerCase()===segment)||'Society';
 const [mobile,setMobile]=useState(false),[ecosystem,setEcosystem]=useState(false),[tools,setTools]=useState(false),[voice,setVoice]=useState(false),[notifications,setNotifications]=useState(false);
 useEffect(()=>{setMobile(false);window.scrollTo(0,0);},[pathname]);
 const current=links[role].find(x=>`/${segment}${x[1]?'/'+x[1]:''}`===pathname)?.[0]||'Overview';const isConsumer=['Worker','Household'].includes(role);
 const org=role==='Society'?'Sabarmati Labour Cooperative':role==='District'?'Ahmedabad District Coordination':role==='National'?'National Coordination':role==='Institution'?'Greenview Community':role==='Worker'?'Ramesh Patel':'Aarav Mehta';
 return <div className={`app-shell ${isConsumer?'consumer-shell':''}`}><a className="skip-link" href="#main" data-testid="skip-content">Skip to content</a>{mobile&&<button data-testid="sidebar-backdrop" aria-label="Close menu" className="sidebar-backdrop" onClick={()=>setMobile(false)}/>}<aside className={`sidebar ${mobile?'is-open':''}`}>
 <Link to={`/${role.toLowerCase()}`} data-testid="brand-link" className="brand"><span className="brand-icon"><Handshake size={26} strokeWidth={1.7}/></span><span>LABOURLINK<small>BETTER WORK. TOGETHER.</small></span></Link>
 <button data-testid="ecosystem-switcher" className="workspace-switch" onClick={()=>setEcosystem(true)}><span className="workspace-icon">{React.createElement(roleIcon[role],{size:19})}</span><span><small>YOUR WORKSPACE</small><strong>{t(role)} {['Society','District','National'].includes(role)?'admin':''}</strong></span><ChevronDown size={15}/></button>
 <div className="nav-group-label">{isConsumer?'MY SPACE':'WORKSPACE'}</div><nav aria-label="Main navigation">{links[role].map(([name,path,Icon],i)=><React.Fragment key={name}>{i===7&&role==='Society'&&<div className="nav-group-label second">COOPERATIVE</div>}<NavLink data-testid={`nav-${path||'overview'}`} end to={`/${role.toLowerCase()}${path?'/'+path:''}`} className={({isActive})=>`nav-item ${isActive?'active':''}`}><Icon size={19} strokeWidth={1.7}/><span>{t(name)}</span>{name==='Verification'&&<span className="nav-count">{state.entities.workers.filter(w=>w.status==='Pending review').length}</span>}{name==='Complaints'&&role==='Society'&&<span className="nav-dot"/>}</NavLink></React.Fragment>)}</nav>
 <div className="sidebar-bottom"><div className="cooperative-note"><HeartHandshake size={25}/><strong>People first.<br/>Cooperative always.</strong><small>Connecting communities with<br/>verified cooperative workers.</small></div><button className="nav-item" data-testid="open-demo-tools" onClick={()=>setTools(true)}><SlidersHorizontal size={18}/><span>{t('Demo tools')}</span><span className="tiny-label">DEMO</span></button><button className="sidebar-person" data-testid="profile-workspace" onClick={()=>setEcosystem(true)}><Avatar name={role==='Worker'?'Ramesh Patel':'Meera Shah'} index={1}/><span><strong>{role==='Worker'?'Ramesh Patel':'Meera Shah'}</strong><small>{role==='Worker'?'Member · Demo':'Workspace administrator · Demo'}</small></span><ChevronRight size={15}/></button></div></aside>
 <div className="main-wrap"><header className="topbar"><div className="breadcrumb"><button className="icon-btn mobile-menu" data-testid="open-sidebar" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={21}/></button><span className="desktop-only">{t(role)} workspace</span><ChevronRight size={14} className="desktop-only"/><strong data-testid="breadcrumb-current">{t(current)}</strong></div><div className="topbar-actions"><div className="language-select"><Globe2 size={16}/><select data-testid="language-select" aria-label="Choose language" value={i18n.language} onChange={e=>{i18n.changeLanguage(e.target.value);localStorage.setItem('ll-language',e.target.value);document.documentElement.lang=e.target.value;}}><option value="en">English</option><option value="hi">हिन्दी</option><option value="gu">ગુજરાતી</option></select></div><button data-testid="open-ecosystem" title="Switch experience" aria-label="Switch experience" className="icon-btn" onClick={()=>setEcosystem(true)}><PanelsTopLeft size={19}/></button><button data-testid="open-notifications" aria-label="Recent activity" title="Recent activity" className="icon-btn notification-btn" onClick={()=>setNotifications(true)}><Bell size={19}/><i/></button><span className="topbar-divider"/><Avatar name={role==='Worker'?'Ramesh Patel':'Meera Shah'} size="small" index={1}/></div></header>
 <div className="organization-strip"><span><span className="org-dot"/>{org} <span className="muted">— Demo</span></span><span className="org-location"><MapPin size={13}/> Ahmedabad, Gujarat</span></div>
 {i18n.language!=='en'&&<div className="translation-notice" data-testid="translation-notice">Draft translation · ગુજરાતી / हिन्दी requires native-speaker review. Detailed research notes may remain in English.</div>}
 <main id="main" className="main-content" tabIndex={-1}>{children}</main>
 <footer className="prototype-footer"><span data-testid="prototype-disclosure"><span className="prototype-dot"/>Interactive prototype · synthetic data · no live transactions</span><span className="desktop-only" data-testid="scenario-id">LL-DEMO-01 <span className="muted">/</span> Society-led. Community-powered.</span></footer>
 </div><button className="voice-fab" data-testid="open-voice" onClick={()=>setVoice(true)} aria-label={t('Voice assistance')} title={t('Voice assistance')}><Mic size={21}/><span>{t('Help')}</span></button>
 <Modal id="ecosystem-modal" open={ecosystem} onClose={()=>setEcosystem(false)} title="One cooperative ecosystem" description="Six distinct experiences · shared synthetic scenario in this local preview."><div className="ecosystem-grid">{roles.map(r=><button key={r} data-testid={`switch-${r.toLowerCase()}`} className={`ecosystem-option ${r===role?'selected':''}`} onClick={()=>{navigate('/'+r.toLowerCase());setEcosystem(false);}}>{React.createElement(roleIcon[r],{size:24})}<strong>{t(r)}</strong><span>{r==='Society'?'Verify, allocate & reconcile':r==='Household'?'Find a trusted service':r==='Worker'?'Your work. Your choice.':r==='Institution'?'Plan multi-worker services':r==='District'?'Coordinate with consent':'Authorized insights only'}</span><ArrowUpRight size={15}/></button>)}</div><p className="small muted" data-testid="ecosystem-disclosure">Separate sites require explicit export/import. Role switching here is a demonstration, not secure authorization.</p></Modal>
 <Modal id="notifications-modal" open={notifications} onClose={()=>setNotifications(false)} title="Recent activity">{state.events.slice(0,6).map(e=><div className="activity-item" key={e.id} data-testid={`notification-${e.id}`}><span className="activity-dot"/><div><strong>{e.entityId} · {e.action}</strong><p>{e.detail}</p><small>{e.actor}</small></div></div>)}</Modal>
 <DemoTools open={tools} onClose={()=>setTools(false)} role={role}/><Voice open={voice} onClose={()=>setVoice(false)} role={role}/></div>;
};