import React,{useEffect,useRef,useState} from 'react';
import {Mic,Volume2,Square} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {useTranslation} from 'react-i18next';
import {Modal,Btn,Notice,Field,useT} from './Common';
export const Voice=({open,onClose,role}:{open:boolean;onClose:()=>void;role:string})=>{
 const t=useT(),{i18n}=useTranslation(),navigate=useNavigate();const [draft,setDraft]=useState(''),[status,setStatus]=useState(''),[listening,setListening]=useState(false);const recognition=useRef<any>(null);
 const lang={en:'en-IN',hi:'hi-IN',gu:'gu-IN'}[i18n.language]||'en-IN';
 useEffect(()=>()=>{recognition.current?.abort();if('speechSynthesis' in window)window.speechSynthesis.cancel();},[]);
 useEffect(()=>{if(!open){recognition.current?.abort();setListening(false);}},[open]);
 const start=()=>{const API=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!API){setStatus(t('Voice demonstration'));return;}const r=new API();recognition.current=r;r.lang=lang;r.continuous=false;r.interimResults=false;r.onresult=(event:any)=>{setDraft(event.results[0][0].transcript);setStatus('Transcript ready · review before using');};r.onerror=()=>{setStatus(`${t('Voice demonstration')} · microphone unavailable or permission denied. Use typed input.`);setListening(false);};r.onend=()=>setListening(false);try{r.start();setListening(true);}catch{setStatus(t('Voice demonstration'));}};
 const read=()=>{if(!('speechSynthesis' in window)){setStatus('Read-aloud unavailable in this browser');return;}const voices=window.speechSynthesis.getVoices();const v=voices.find(v=>v.lang.startsWith(lang.slice(0,2)));if(!v){setStatus('No matching language voice available. Typed content remains available.');return;}const u=new SpeechSynthesisUtterance(draft||t('Read this offer'));u.lang=lang;u.voice=v;window.speechSynthesis.cancel();window.speechSynthesis.speak(u);};
 return <Modal id="voice-modal" open={open} onClose={onClose} title={t('Voice assistance')} description={t('Microphone permission is optional. Browser speech may use remote processing.')}><Notice id="voice-privacy">{t('Typed input is always available. Confirm important actions on screen.')}</Notice><Field label="Task description" id="voice-transcript"><textarea id="voice-transcript" data-testid="voice-transcript" value={draft} onChange={e=>setDraft(e.target.value)} placeholder={t('Show today’s jobs')}/></Field><div className="button-row"><Btn id="voice-start" onClick={start} disabled={listening}><Mic size={16}/>{t('Start microphone')}</Btn><Btn id="voice-stop" kind="secondary" disabled={!listening} onClick={()=>{recognition.current?.stop();setListening(false);}}><Square size={14}/>{t('Stop')}</Btn><Btn id="voice-read" kind="secondary" onClick={read}><Volume2 size={16}/>{t('Read aloud')}</Btn></div><div className="preset-list">{['Show today’s jobs','Read this offer','I have arrived'].map((p,i)=><button data-testid={`voice-preset-${i}`} key={p} onClick={()=>{setDraft(t(p));setStatus(t('Voice demonstration')+' · preset transcript');}}>{t(p)}</button>)}</div>{status&&<p className="small muted" role="status" data-testid="voice-status">{status}</p>}<Btn id="voice-use-draft" disabled={!draft.trim()} onClick={()=>{navigate(role==='Household'?'/household/request':role==='Worker'?'/worker/jobs':'/society/jobs');onClose();}}>{t('Continue')} →</Btn></Modal>;
};