import {z} from 'zod';
import {DemoState} from './schema';
const report=z.object({id:z.string(),organizationId:z.string(),organizationName:z.string(),region:z.string(),periodStart:z.string(),periodEnd:z.string(),refreshedAt:z.string(),scope:z.literal('authorized-capacity-summary'),requested:z.number().int().nonnegative(),proposed:z.number().int().nonnegative(),committed:z.number().int().nonnegative(),accepted:z.number().int().nonnegative(),attended:z.number().int().nonnegative(),service:z.string(),societyCount:z.number().int().nonnegative(),relationshipPath:z.array(z.string()),method:z.string(),complete:z.boolean()}).strict().refine(x=>x.attended<=x.accepted&&x.accepted<=x.committed&&x.committed<=x.proposed,'Capacity counters are inconsistent');
export const aggregateSchema=z.object({schemaVersion:z.literal(1),scenarioId:z.literal('LL-DEMO-01'),originApp:z.enum(['District','National']),scope:z.literal('aggregate-only'),synthetic:z.literal(true),demoClock:z.string(),reports:z.array(report).max(100),events:z.array(z.object({id:z.string(),organizationId:z.string(),action:z.string(),at:z.string()}).strict()).max(1000)}).strict();
export type Aggregate=z.infer<typeof aggregateSchema>;
export function districtAggregate(state:DemoState):Aggregate{const b=state.entities.bulkRequirements[0],end=new Date(b.start);end.setDate(end.getDate()+b.days-1);const a=state.entities.allocations.filter(a=>state.entities.affiliations.some(f=>f.societyId===a.societyId&&f.status==='Active'&&f.scope.includes('capacity-sharing')));return {schemaVersion:1,scenarioId:'LL-DEMO-01',originApp:'District',scope:'aggregate-only',synthetic:true,demoClock:state.demoClock,reports:[{id:`DIST-A-${b.start}`,organizationId:'DIST-A',organizationName:'Ahmedabad District Coordination — Demo',region:'Ahmedabad',periodStart:b.start,periodEnd:end.toISOString().slice(0,10),refreshedAt:state.demoClock,scope:'authorized-capacity-summary',requested:b.requested,proposed:a.reduce((n,x)=>n+x.proposed,0),committed:a.reduce((n,x)=>n+x.committed,0),accepted:a.reduce((n,x)=>n+x.accepted,0),attended:a.reduce((n,x)=>n+x.attended,0),service:b.service,societyCount:a.length,relationshipPath:['Participating societies','Ahmedabad district · Demo','Optional state/regional relationship — unverified','National summary permission only'],method:'Rule-based capacity proposals; no named-worker confirmation',complete:true}],events:[{id:`AGG-${state.demoClock}`,organizationId:'DIST-A',action:'Authorized aggregate exported',at:state.demoClock}]};}
export const initialAggregate=():Aggregate=>({schemaVersion:1,scenarioId:'LL-DEMO-01',originApp:'National',scope:'aggregate-only',synthetic:true,demoClock:'2026-07-14T09:00:00+05:30',reports:[{id:'SURAT-STALE',organizationId:'DIST-DEMO-S',organizationName:'Surat Coordination — Demo',region:'Surat',periodStart:'2026-05-01',periodEnd:'2026-05-30',refreshedAt:'2026-05-31T09:00:00+05:30',scope:'authorized-capacity-summary',requested:60,proposed:40,committed:20,accepted:0,attended:0,service:'Cleaning',societyCount:2,relationshipPath:['Demo district','Unverified regional relationship'],method:'Synthetic capacity submission; stale, not current demand',complete:false}],events:[]});
export function mergeAggregate(local:Aggregate,incoming:Aggregate):Aggregate{
 const parsed=aggregateSchema.parse(incoming);if(new Set(parsed.reports.map(r=>r.id)).size!==parsed.reports.length)throw new Error('Duplicate reports in the file');
 if(parsed.events.length&&parsed.events.every(e=>local.events.some(x=>x.id===e.id)))throw new Error('Duplicate aggregate events: already imported');
 const reports=[...local.reports];for(const r of parsed.reports){const overlap=reports.find(x=>x.organizationId===r.organizationId&&x.periodStart<=r.periodEnd&&x.periodEnd>=r.periodStart);if(overlap)throw new Error(`Duplicate or overlapping reporting period for ${r.organizationName}; request a correction instead of double-counting.`);reports.push(r);}
 return aggregateSchema.parse({...local,demoClock:parsed.demoClock>local.demoClock?parsed.demoClock:local.demoClock,reports,events:[...local.events,...parsed.events]});
}