import { DemoState, Worker, Booking } from './schema';
export const DEMO_CLOCK='2026-07-14T09:00:00+05:30';
export const TRADES=['Plumbing','Electrical','Cleaning','Carpentry','Painting','Gardening','Driving','Domestic help','Caregiving','Technicians'];
export const SOCIETY_NAMES=['Sabarmati','Sahyog','Udaan','Navjeevan'];
const first=['Ramesh','Suresh','Kavita','Mahesh','Anita','Vijay','Meena','Arjun','Sunita','Rajesh','Priya','Kiran','Deepak','Nisha','Bharat','Rekha'];
const last=['Patel','Shah','Parmar','Solanki','Rathod','Desai','Chauhan','Joshi'];
const stamp={updatedAt:DEMO_CLOCK};
export function createSeed(stage='default'):DemoState {
 const workers:Worker[]=Array.from({length:124},(_,i)=>({id:`WRK-${String(i+1).padStart(3,'0')}`,...stamp,name:i===0?'Ramesh Patel':`${first[i%first.length]} ${last[Math.floor(i/first.length)%last.length]}`,societyId:'SOC-A',trade:TRADES[i%10],experience:2+i%14,area:['Navrangpura','Paldi','Satellite','Vastrapur'][i%4],membershipRef:`SAB-${1001+i}`,status:i<96?'Verified':i<114?'Pending review':'Corrections requested',membership:i<96,identity:i<96,skillVerified:i<96,certificate:i<20,available:i<72,reviewer:i<96?'Meera Shah':'',source:i<96?'Society roster and demonstration trade assessment':'Imported synthetic roster',reviewDate:i<96?'2026-07-01':'',reviewDue:i<96?'2027-07-01':'',reason:i>=114?'Membership reference requires clarification':'',skills:[{id:`SK-${i+1}`,name:TRADES[i%10],verified:i<96}],availability:[{start:'2026-07-14T08:00:00+05:30',end:'2026-08-14T18:00:00+05:30',available:i<72}]}));
 const statuses:Booking['status'][]=['Requested','In progress','Accepted','On the way','Offer sent','Requested','Accepted','Arrived','Offer sent','In progress','Requested','Accepted','Requested','Offer sent','Accepted','Completed','Completed','Completed','Completed','Completed','Completed','Completed','Completed','Completed'];
 const bookings:Booking[]=statuses.map((status,i)=>({id:`BK-${1024+i}`,...stamp,workerId:workers[i].id,societyId:'SOC-A',customer:['Aarav Mehta','Greenview Residency','Nisha Shah','Dev Patel','Anjali Desai','Riverfront Community'][i%6],service:workers[i].trade,area:workers[i].area,start:`2026-07-${i<15?'14':'13'}T${String(10+i%4).padStart(2,'0')}:00:00+05:30`,end:`2026-07-${i<15?'14':'13'}T${String(12+i%4).padStart(2,'0')}:00:00+05:30`,status,description:i===0?'Leaking kitchen tap and washbasin pipe inspection. Customer supplies replacement parts.':'Scheduled household / community service. Materials supplied by customer; worker arranges local travel.',quoteId:`QT-${1024+i}-1`}));
 const state:DemoState={schemaVersion:1,scenarioId:'LL-DEMO-01',originApp:'Society',demoClock:DEMO_CLOCK,synthetic:true,entities:{
 societies:SOCIETY_NAMES.map((n,i)=>({id:`SOC-${'ABCD'[i]}`,...stamp,name:`${n} Labour Cooperative — Demo`,shortName:n,services:TRADES})),
 affiliations:SOCIETY_NAMES.map((_,i)=>({id:`AFF-${i+1}`,...stamp,societyId:`SOC-${'ABCD'[i]}`,organizationId:'DIST-A',type:'Coordination authorization',status:'Active',scope:['capacity-sharing','consented-shortfall'],effectiveFrom:'2026-01-01',effectiveTo:'2026-12-31'})),workers,bookings,
 quotes:bookings.map((b,i)=>({id:b.quoteId,...stamp,bookingId:b.id,version:1,total:i===0?50000:(600+i%5*200)*100,workerEarning:i===0?45000:(600+i%5*200)*90,societyAllocation:i===0?5000:(600+i%5*200)*10,status:'Approved',reason:'Example cooperative rule—not a universal commission.',approvalRef:'DEMO-AGM-2026-04 / Customer approval v1'})),
 payments:bookings.map((b,i)=>({id:`PAY-${b.id}`,...stamp,bookingId:b.id,amount:i===0?50000:(600+i%5*200)*100,status:i<15?'Unpaid':i<18?'Cash reported':i<21?'Digital confirmed':'Cash confirmed',method:i<15?'None':i<18?'Cash':i<21?'Digital':'Cash',holder:i<15?'None':i<18?'Worker':i<21?'Society':'Worker',note:'Synthetic payment record; no money moved.'})),
 settlements:bookings.map((b,i)=>({id:`SET-${b.id}`,...stamp,bookingId:b.id,workerEarning:i===0?45000:(600+i%5*200)*90,societyAllocation:i===0?5000:(600+i%5*200)*10,status:i<18?'Not due':'Due',note:'Example cooperative rule—not a universal commission.'})),
 complaints:[{id:'CMP-001',...stamp,bookingId:'BK-1040',title:'Cash receipt needs confirmation',reporter:'Customer · Demo',status:'Reported',notes:['Customer reports paying cash. Awaiting worker and customer confirmation.']},{id:'CMP-002',...stamp,bookingId:'BK-1043',title:'Service arrival time disputed',reporter:'Customer · Demo',status:'Under review',notes:['Arrival-time allegation is unverified. Worker response requested.']}],
 bulkRequirements:[{id:'BR-0400',...stamp,service:'Cleaning',requested:400,start:'2026-07-20',days:30,hours:8,location:'Ahmedabad community facilities — Demo',status:'Under review',consent:false,coordinated:false,details:{}}],
 allocations:[100,80,120,100].map((proposed,i)=>({id:`AL-${i+1}`,...stamp,bulkId:'BR-0400',societyId:`SOC-${'ABCD'[i]}`,proposed,committed:0,accepted:0,attended:0,status:'Proposed'})),
 benefits:[{id:'BEN-001',...stamp,title:'e-Shram information & guidance',kind:'Official information',source:'https://eshram.gov.in/faqs',checkedAt:'2026-07-14',caveat:'Information only. Registration does not establish cooperative membership, scheme eligibility, or automatic insurance.'},{id:'BEN-002',...stamp,title:'Member insurance information',kind:'Society information',source:'Society-submitted demonstration note',checkedAt:'2026-07-14',caveat:'Unverified. No insurer policy or coverage has been confirmed.'},{id:'BEN-003',...stamp,title:'Tools for the next opportunity',kind:'Demo cooperative support',source:'Synthetic society support programme',checkedAt:'2026-07-14',caveat:'Demo cooperative tool assistance—not a government scheme. Requests require review; no loan is approved.'}],
 policies:[{id:'POL-001',...stamp,title:'Household service & settlement rule',version:1,effectiveDate:'2026-04-01',approvalRef:'DEMO-AGM-2026-04',rule:'Illustrative ₹500 customer total = ₹450 worker earning + ₹50 society allocation. Example cooperative rule—not a universal commission. Additional work needs customer approval.'},{id:'POL-002',...stamp,title:'Verification & worker consent',version:1,effectiveDate:'2026-04-01',approvalRef:'DEMO-BOARD-2026-02',rule:'Membership, identity, skill and certification are separate checks. Worker acceptance is voluntary. A decline does not incur a penalty.'}],
 history:['Plumbing','Electrical','Cleaning','Carpentry'].flatMap((trade,t)=>Array.from({length:28},(_,i)=>({id:`H-${t}-${i}`,trade,date:new Date(Date.UTC(2026,5,16+i)).toISOString().slice(0,10),jobs:[4,6,5,8][t]+i%4,hours:[2,2,3,3][t]}))),recommendations:[]},events:[
 {id:'EV-SEED-1',at:'2026-07-14T08:45:00+05:30',actor:'Meera Shah · Demo',entityId:'WRK-001',action:'Worker verified',detail:'Membership and plumbing skill reviewed against synthetic society records.'},
 {id:'EV-SEED-2',at:'2026-07-14T08:30:00+05:30',actor:'Household · Demo',entityId:'BK-1024',action:'New booking requested',detail:'Plumbing · Navrangpura · ₹500 approved example quote.'},
 {id:'EV-SEED-3',at:'2026-07-14T08:15:00+05:30',actor:'Worker · Demo',entityId:'BK-1039',action:'Cash payment reported',detail:'Customer confirmation needed. Digital payment is blocked.'},
 {id:'EV-SEED-4',at:'2026-07-14T08:00:00+05:30',actor:'Institution · Demo',entityId:'BR-0400',action:'Bulk requirement received',detail:'400 proposed positions · no workers confirmed.'}]};
 if(stage==='cash'){state.entities.bookings[0].status='Completed';state.entities.payments[0]={...state.entities.payments[0],status:'Cash reported',method:'Cash',holder:'Worker'};}
 if(stage==='conflict'){state.entities.bookings[1]={...state.entities.bookings[1],workerId:'WRK-001',service:'Plumbing',start:bookings[0].start,end:bookings[0].end,status:'Accepted'};}
 if(stage==='unlinked'){state.entities.affiliations[0].status='Unlinked';}
 if(stage==='no-data'){state.entities.history=[];}
 if(stage==='completed'){state.entities.bookings[0].status='Completed';state.entities.payments[0]={...state.entities.payments[0],status:'Digital confirmed',method:'Digital',holder:'Society'};state.entities.settlements[0].status='Due';}
 return state;
}