import React,{useState} from 'react';
import {useNavigate,Link} from 'react-router-dom';
import {Users,ShieldCheck,BriefcaseBusiness,Wallet,Plus,CalendarDays,ArrowUpRight,ArrowRight,ChevronRight,Clock,AlertCircle,MessageSquare,Presentation,Download,Leaf} from 'lucide-react';
import {useDemo} from '../demo/store';
import {availableWorkers,activeStatuses,ledgerDue,money} from '../demo/selectors';
import {PageHead,Btn,Stat,useT} from '../components/Common';
import {JobsTable} from './Jobs';
export default function Overview(){
 const {state}=useDemo(),navigate=useNavigate(),t=useT();const [date,setDate]=useState('2026-07-14');const e=state.entities;
 const verified=e.workers.filter(w=>w.status==='Verified').length,pending=e.workers.filter(w=>w.status==='Pending review').length,active=e.bookings.filter(b=>activeStatuses.includes(b.status)).length;
 const due=e.bookings.reduce((n,b)=>n+ledgerDue(state,b.id).worker+ledgerDue(state,b.id).society,0),available=availableWorkers(state,date).length,cash=e.payments.filter(p=>p.status==='Cash reported').length,complaints=e.complaints.filter(c=>c.status!=='Closed').length;
 const chart=Array.from({length:7},(_,i)=>{const d=`2026-07-${String(7+i).padStart(2,'0')}`;return{day:['Tue','Wed','Thu','Fri','Sat','Sun','Mon'][i],value:e.history.filter(h=>h.date===d).reduce((n,h)=>n+h.jobs,0)};});
 return <><PageHead eyebrow="YOUR COOPERATIVE, AT A GLANCE" title="Society overview" subtitle="A little clarity for your day. A lot of possibility for your people."><label className="date-select"><CalendarDays size={14}/><input type="date" aria-label="Capacity date" data-testid="overview-date" value={date} onChange={ev=>setDate(ev.target.value)}/></label><Btn id="overview-add-worker" onClick={()=>navigate('/society/workers?add=1')}><Plus size={15}/>{t('Add worker')}</Btn></PageHead>
 <div className="stats-grid"><Stat id="metric-verified" label="Active verified workers" value={verified} note={`${e.workers.length} total registered profiles`} icon={Users} onClick={()=>navigate('/society/workers?status=Verified')}/><Stat id="metric-pending" label="Pending verification" value={pending} note="Ready for your review" icon={ShieldCheck} tone="amber" onClick={()=>navigate('/society/verification')}/><Stat id="metric-active" label="Active jobs" value={active} note={`${e.bookings.filter(b=>b.status==='Requested').length} new requests to review`} icon={BriefcaseBusiness} tone="blue" onClick={()=>navigate('/society/jobs')}/><Stat id="metric-unsettled" label="Unsettled amount" value={money(due)} note="Confirmed payments, settlement due" icon={Wallet} tone="rose" onClick={()=>navigate('/society/payments')}/></div>
 <div className="overview-grid"><div><section className="section-panel"><div className="section-header"><div><h2 data-testid="jobs-section-title">Today's work</h2><p data-testid="jobs-section-subtitle">Every request. The right people. A clear next step.</p></div><Link className="text-link" data-testid="overview-all-jobs" to="/society/jobs">{t('View all')} <ArrowUpRight size={13}/></Link></div><JobsTable bookings={e.bookings.filter(b=>b.start.slice(0,10)===date).slice(0,5)} compact/><div className="table-footer"><span data-testid="today-job-count">{e.bookings.filter(b=>b.start.slice(0,10)===date).length} jobs scheduled for this day</span><Link data-testid="manage-schedule" to="/society/jobs">Manage schedule →</Link></div></section>
 <div className="lower-grid"><section className="section-panel"><div className="section-header"><div><h2>Workforce availability</h2><p>Selected date · 10:00–12:00 IST</p></div><Leaf size={16} color="#93a185"/></div><div className="capacity-content"><div className="capacity-ring" style={{'--available':`${available/e.workers.length*100}%`,'--verified':`${verified/e.workers.length*100}%`} as React.CSSProperties}><div className="ring-label"><strong data-testid="available-worker-count">{available}</strong><small>AVAILABLE</small></div></div><div className="capacity-legend"><div className="legend-row"><i style={{background:'#0b6e4f'}}/>Available <strong>{available}</strong></div><div className="legend-row"><i style={{background:'#bfd0a6'}}/>Busy / unavailable<strong>{verified-available}</strong></div><div className="legend-row"><i style={{background:'#ecdfb8'}}/>Awaiting verification<strong>{e.workers.length-verified}</strong></div></div></div></section>
 <section className="section-panel"><div className="section-header"><div><h2>Service demand</h2><p>Synthetic history · last 7 recorded days</p></div><Link data-testid="view-demand-planning" className="text-link" to="/society/planning"><ArrowUpRight size={15}/></Link></div><div className="mini-chart" data-testid="demand-chart">{chart.map((c,i)=><div className="chart-col" key={c.day} title={`${c.day}: ${c.value} demo requests`}><div className="chart-bar" style={{height:`${c.value/40*95}px`}}/><small>{c.day}</small></div>)}</div></section></div></div>
 <div className="overview-side"><section className="attention-panel"><div className="attention-heading"><AlertCircle size={16}/><h2>Needs your attention</h2><span>{[pending,cash,complaints].filter(n=>n>0).length}</span></div>{[{icon:ShieldCheck,title:`${pending} profiles to verify`,sub:'Help your members get work-ready',route:'verification'},{icon:Wallet,title:`${cash} cash payments to reconcile`,sub:'A clear record for everyone',route:'payments'},{icon:MessageSquare,title:`${complaints} open complaints`,sub:'Listen, review and find a resolution',route:'complaints'}].map((a,i)=><button data-testid={`attention-${a.route}`} className="attention-item" key={a.route} onClick={()=>navigate(`/society/${a.route}`)}><span className="attention-icon"><a.icon size={17}/></span><div><strong>{a.title}</strong><p>{a.sub}</p></div><ChevronRight size={14}/></button>)}</section>
 <section className="section-panel activity-panel"><div className="section-header"><h2>Recent activity</h2><Clock size={15} color="#93a185"/></div><div className="activity-list">{state.events.slice(0,3).map(ev=><div className="activity-item" key={ev.id} data-testid={`activity-${ev.id}`}><span className="activity-dot"/><div><strong>{ev.action.charAt(0).toUpperCase()+ev.action.slice(1)}</strong><p>{ev.entityId} · {ev.detail}</p><small>{ev.actor.split(' · ')[0]} · Demo clock</small></div></div>)}</div></section></div></div>
 <div className="presentation-banner"><span data-testid="overview-governance-note">Decisions belong to the cooperative. Every action leaves a clear record.</span><a href="/downloads/LABOURLINK-six-slide.pptx" download data-testid="overview-download-pptx"><Presentation size={15}/>LABOURLINK presentation <Download size={13}/></a></div></>;
}